#!/usr/bin/env bash
# Re-apply the iOS App Store packaging fixes that `tauri ios init` does NOT do.
#
# src-tauri/gen/apple/ is gitignored and regenerated by `tauri ios init`, so run this AFTER any
# re-init and BEFORE `npm run tauri ios build -- --export-method app-store-connect`.
#
# Fixes the two App Store validation rejections we hit on the first 0.8.3 TestFlight upload:
#   1. `libapp.a` copied into Sampatti.app → Apple error 90171 ("standalone executables or
#      libraries are not permitted"). Tauri's project.yml lists Externals/ (which holds libapp.a)
#      as a source with NO buildPhase, so XcodeGen sweeps it into Copy Bundle Resources. Setting
#      `buildPhase: none` keeps it LINKED (via the separate `framework: libapp.a` dependency) but
#      stops it being copied.
#   2. App icon carries an alpha channel → Apple error 90717 ("large app icon … can't be
#      transparent or contain an alpha channel"). Flatten the generated AppIcon PNGs to opaque RGB.
# Plus: re-assert signing (DEVELOPMENT_TEAM + automatic) in project.yml so it survives `xcodegen`
# (Xcode's "Automatically manage signing" writes it into the .pbxproj, which xcodegen overwrites).
set -euo pipefail
cd "$(git rev-parse --show-toplevel)/src-tauri/gen/apple"
TEAM="7LC9LFH33N"

# 1 + signing: patch project.yml idempotently, then regenerate the Xcode project from it.
python3 - "$TEAM" <<'PY'
import sys, re
team = sys.argv[1]
t = open("project.yml").read()
# Externals → buildPhase: none (skip if already set)
t = re.sub(r'(\n      - path: Externals)(?!\n        buildPhase)',
           r'\1\n        buildPhase: none', t)
# signing in settings.base, right after ENABLE_BITCODE (skip if already present)
if 'DEVELOPMENT_TEAM' not in t:
    t = t.replace('        ENABLE_BITCODE: false\n',
                  '        ENABLE_BITCODE: false\n'
                  '        DEVELOPMENT_TEAM: "%s"\n'
                  '        CODE_SIGN_STYLE: Automatic\n' % team)
open("project.yml", "w").write(t)
print("project.yml patched")
PY
xcodegen generate >/dev/null
echo "✓ project.yml patched + xcodeproj regenerated (libapp.a unbundled, signing set)"

# 2: strip the alpha channel from the generated iOS app icons (flatten on white; they are
# full-bleed so this is lossless).
python3 - <<'PY'
from PIL import Image
import glob
n = 0
for f in glob.glob("Assets.xcassets/AppIcon.appiconset/*.png"):
    im = Image.open(f)
    if im.mode != "RGB":
        im = im.convert("RGBA")
        bg = Image.new("RGB", im.size, (255, 255, 255))
        bg.paste(im, mask=im.split()[3])
        bg.save(f)
        n += 1
print(f"flattened {n} app-icon PNGs to opaque RGB")
PY
echo "✓ iOS packaging fixes applied — now run:"
echo "    npm run tauri ios build -- --export-method app-store-connect"
